fail_fast: true

repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
    rev: v0.4.10
    hooks:
      # Run the linter.
      - id: ruff
        stages: [ pre-commit ]
        args: [ --fix ]
      # Run the formatter.
      - id: ruff-format
        stages: [ pre-commit ]

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.7.0
    hooks:
      - id: mypy
        exclude: ^tests/
        verbose: true
        args: [--ignore-missing-imports]
        additional_dependencies: ['types-requests']
        entry: mypy

  - repo: https://github.com/compilerla/conventional-pre-commit
    rev: v3.1.0
    hooks:
      - id: conventional-pre-commit
        stages: [commit-msg]
        args: []
