on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'


jobs:
  pypi-publish:
    name: Publish package to Pypi
    uses: wherobots/ci-tools/.github/workflows/publish-pypi.yaml@main
    with:
      pypi_repo_name: airflow-providers-wherobots
      python_version: 3.9
    secrets: inherit