name: CI for unit testing

on:
  workflow_call:

jobs:
  execute-tests:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Install Python
        id: setup-python
        uses: actions/setup-python@v4
        with:
          python-version: 3.8
      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          version: "0.7.12"
      - name: Unit tests
        run: uv run pytest tests/unit_tests --disable-warnings --full-trace
        shell: bash
      - name: Integration tests
        run: uv run pytest tests/integration_tests --disable-warnings --full-trace
        shell: bash
        env:
          PROD_API_TOKEN: ${{ secrets.PROD_API_TOKEN }}
