name: CI for unit testing

on:
  workflow_call:

jobs:
  execute-tests:
    name: Run tests
    runs-on: depot-ubuntu-24.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Install Python
        id: setup-python
        uses: actions/setup-python@v4
        with:
          python-version: 3.8
      - name: Install and configure Poetry
        uses: snok/install-poetry@v1
        with:
          version: 1.8.5
          virtualenvs-create: true
          virtualenvs-in-project: true
      - name: Install dependencies
        working-directory: .
        run: poetry install --no-interaction --no-ansi -vvv
        shell: bash
      - name: Unit tests
        run: poetry run pytest tests/unit_tests --disable-warnings --full-trace
        shell: bash
      - name: Integration tests
        run: poetry run pytest tests/integration_tests --disable-warnings --full-trace
        shell: bash
        env:
          PROD_API_TOKEN: ${{ secrets.PROD_API_TOKEN }}